### ISSUE TITLE
large text files get

### ISSUE THREAD

**Issue by DovieW** [DovieW/microbook-maker#3]
if you try war and peace it gets stuck at page 57

nearly 600,000 word book

**Comment by DovieW** [comment]
on font size 7 its get stuck at sheet 48.5. theres an error in the logs:
0|mbm  | ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
0|mbm  |     at new Callback (/home/dovie/repos/microbook-maker/be/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:62:35)
0|mbm  |     at CallbackRegistry.create (/home/dovie/repos/microbook-maker/be/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:108:26)
0|mbm  |     at Connection._rawSend (/home/dovie/repos/microbook-maker/be/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:224:26)
0|mbm  |     at CDPSessionImpl.send (/home/dovie/repos/microbook-maker/be/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:433:78)
0|mbm  |     at ExecutionContext._ExecutionContext_evaluate (/home/dovie/repos/microbook-maker/be/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:244:46)
0|mbm  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|mbm  |     at async ExecutionContext.evaluate (/home/dovie/repos/microbook-maker/be/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:145:16)
0|mbm  |     at async run (/home/dovie/repos/microbook-maker/be/index.js:65:5)
0|mbm  |     at async Immediate.<anonymous> (/home/dovie/repos/microbook-maker/be/index.js:39:7)
0|mbm  | ERROR: ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

**Comment by DovieW** [comment]
723d84ff44a4e63952a55f654511c059d7040b7b
